package com.su.clubfair.data.net

import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.IOException

/**
 * Every call the app makes to su-server.
 *
 * Hand-written over OkHttp rather than generated by Retrofit. The API is a dozen
 * endpoints and su-server answers failures as `{"error": "<Thai>"}` with a
 * meaningful status — surfacing that through Retrofit needs a custom converter
 * and error-body parsing anyway, so the abstraction would add a layer without
 * removing any work, and it would put the error mapping somewhere less obvious
 * than [request].
 *
 * Nothing here throws for an expected outcome. A dead network and a rejection are
 * both [ApiResult] cases, because both are things that happen to a student
 * standing in a hall rather than programming errors.
 */
class ClubFairApi(
    private val baseUrl: String,
    private val client: OkHttpClient,
    /**
     * Reads the stored token. A function rather than a value because the token
     * changes underneath a long-lived API instance — at sign-in, at sign-out —
     * and capturing it once would send a stale one for the rest of the process.
     */
    private val tokenProvider: suspend () -> String?,
) {
    private val json = Json {
        // The server is free to add fields without every client needing a
        // release. Without this, one new key in a response is a crash.
        ignoreUnknownKeys = true
        explicitNulls = false
    }

    private val jsonMedia = "application/json; charset=utf-8".toMediaType()

    // ---- Auth (no token) --------------------------------------------------

    suspend fun signInWithGoogle(idToken: String): ApiResult<SessionDto> =
        post("auth/google", GoogleSignInRequest(idToken), authenticated = false)

    suspend fun signInWithPassword(phone: String, password: String): ApiResult<SessionDto> =
        post("auth/login", PasswordLoginRequest(phone, password), authenticated = false)

    suspend fun register(body: RegisterRequest): ApiResult<SessionDto> =
        post("auth/register", body, authenticated = false)

    // ---- Public ----------------------------------------------------------

    suspend fun booths(): ApiResult<List<BoothDto>> = get("booths", authenticated = false)

    suspend fun zones(): ApiResult<List<ZoneDto>> = get("zones", authenticated = false)

    // ---- Signed in -------------------------------------------------------

    suspend fun me(): ApiResult<UserDto> = get("me")

    suspend fun updateProfile(body: UpdateProfileRequest): ApiResult<UserDto> =
        send("PATCH", "me", body)

    /**
     * Adds the password a Google-only account signs in with.
     *
     * Answers `{"ok": true}` rather than the account, so the caller that wants
     * the updated `has_password` and `profile_complete` has to re-read them —
     * which the profile update immediately after this one already does.
     */
    suspend fun setPassword(password: String): ApiResult<OkDto> =
        send("PUT", "me/password", SetPasswordRequest(password))

    suspend fun progress(): ApiResult<ProgressDto> = get("progress")

    suspend fun checkIns(): ApiResult<List<CheckInDto>> = get("checkins")

    suspend fun recordCheckIn(body: CheckInRequest): ApiResult<CheckInResultDto> =
        post("checkins", body)

    suspend fun announcements(): ApiResult<List<AnnouncementDto>> = get("announcements")

    suspend fun toggleReaction(announcementId: Long, emoji: String): ApiResult<ReactionStateDto> =
        post("announcements/$announcementId/reactions", ReactionRequest(emoji))

    // ---- Plumbing --------------------------------------------------------

    private suspend inline fun <reified T> get(
        path: String,
        authenticated: Boolean = true,
    ): ApiResult<T> = request(Request.Builder().url(url(path)).get(), authenticated)

    private suspend inline fun <reified B, reified T> post(
        path: String,
        body: B,
        authenticated: Boolean = true,
    ): ApiResult<T> = send("POST", path, body, authenticated)

    private suspend inline fun <reified B, reified T> send(
        method: String,
        path: String,
        body: B,
        authenticated: Boolean = true,
    ): ApiResult<T> {
        val encoded = json.encodeToString(body).toRequestBody(jsonMedia)
        return request(Request.Builder().url(url(path)).method(method, encoded), authenticated)
    }

    private fun url(path: String) = "${baseUrl.trimEnd('/')}/clubfair/$path"

    /**
     * Runs one call and turns everything that can happen into an [ApiResult].
     *
     * `Dispatchers.IO` here rather than at every call site, so no caller can
     * forget and block a frame on a socket.
     */
    private suspend inline fun <reified T> request(
        builder: Request.Builder,
        authenticated: Boolean,
    ): ApiResult<T> = withContext(Dispatchers.IO) {
        if (authenticated) {
            val token = tokenProvider()
                // No token at all, answered without a round trip.
                //
                // This used to be a 401, on the argument that "signed out" is then
                // a single condition the caller handles one way. It cannot be one
                // any more: a 401 now means *the server rejected the token we
                // sent*, and `FairRepository` ends the session when it sees one.
                // Reusing it here would make every authenticated call made while
                // signed out — the refresh on launch makes several — look like an
                // expired session, and the sign-in screen would accuse a student
                // who had simply never signed in of having been logged out.
                ?: return@withContext ApiResult.Failure(MissingToken, null)
            builder.header("Authorization", "Bearer $token")
        }

        try {
            client.newCall(builder.build()).execute().use { response ->
                val payload = response.body.string()

                if (!response.isSuccessful) {
                    // The server's own message, which is Thai and written for a
                    // student. Falls back to null rather than inventing English
                    // copy here — the caller has a resource string for that.
                    val message = runCatching {
                        json.decodeFromString<ApiErrorDto>(payload).error
                    }.getOrNull()
                    return@use ApiResult.Failure(response.code, message)
                }

                // A 204, or an endpoint whose body the caller ignores.
                if (payload.isBlank() && T::class == Unit::class) {
                    @Suppress("UNCHECKED_CAST")
                    return@use ApiResult.Success(Unit as T)
                }

                ApiResult.Success(json.decodeFromString<T>(payload))
            }
        } catch (io: IOException) {
            // No route, no DNS, timeout, connection reset. The student is
            // probably in a hall with bad signal — expected operating conditions,
            // not an error.
            ApiResult.Offline(io)
        } catch (decode: SerializationException) {
            // A 2xx whose body did not parse: a contract mismatch between client
            // and server, not a network condition. Reporting it as Offline would
            // make the app queue and retry forever against a response it can
            // never read, so it is a Failure with a status no server sends.
            Log.w("ClubFairApi", "unreadable response body", decode)
            ApiResult.Failure(UnreadableResponse, null)
        }
    }

    companion object {
        /**
         * The status for "the server answered 2xx and the body did not parse".
         *
         * Not a real HTTP code, and negative so it can never collide with one.
         */
        const val UnreadableResponse = -1

        /**
         * The status for "this call needs a token and there isn't one".
         *
         * Negative for the same reason [UnreadableResponse] is, and distinct from
         * 401 for the reason spelled out in [request]: only the server can decide
         * that a token is no longer good, and only that decision may end a
         * session.
         */
        const val MissingToken = -2
    }
}
